// This file is automatically generated.
// Please do not change this file!
interface CssExports {
	ldsRing: string;
	loaderWrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
